### Add promotion
POST http://localhost:8080/promotion-management/promotions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name" : "Black Friday promotiono",
  "percentValue" : "50",
  "createdDate" : "2000-01-01T21:34:55",
  "endDate" : "2000-01-08T21:34:55"
}

### Update promotion
PUT http://localhost:8080/promotion-management/promotions/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id" : "1",
  "name" : "Monday promotion",
  "percentValue" : "30"
}