### Realize transaction
POST http://localhost:8080/user-management/users/1/transaction-management/transactions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "user" : {
    "id" : "1"
  },
  "product" : {
    "id" : "1"
  }
}