### Change user password
PATCH http://localhost:8080/user-management/users/1/password
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "password" : "newPassword"
}

### Change user email
PATCH http://localhost:8080/user-management/users/1/email
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email" : "scsplayer2@gmail.com"
}

### Find user
GET http://localhost:8080/user-management/users/2
Authorization: Bearer {{auth_token}}

### Delete user
DELETE http://localhost:8080/user-management/users/1
Authorization: Bearer {{auth_token}}