# JOIN TABLES
DROP TABLE USER_ROLE;

# ENTITY TABLES
DROP TABLE COMMENT;
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;
DROP TABLE ADDRESS;
DROP TABLE ROLE;
DROP TABLE TOKEN;
DROP TABLE PERSON;
DROP TABLE USER;

