# JOIN TABLES
DROP TABLE USER_ROLE;

# ENTITY TABLES
DROP TABLE TRANSACTION;
DROP TABLE REVIEW;
DROP TABLE PROMOTION;
DROP TABLE PRODUCT;
DROP TABLE CATEGORY;
DROP TABLE ADDRESS;
DROP TABLE ROLE;
DROP TABLE TOKEN;
DROP TABLE PERSON;
DROP TABLE USER;