### Add user address
POST http://localhost:8080/user-management/users/1/address-management/addresses
Content-Type: application/json

{
  "country" : "Poland",
  "location" : "Kielce",
  "zipCode" : "30-000",
  "street" : "warszawska 3"
}

### Update address country
PATCH http://localhost:8080/user-management/users/1/address-management/addresses/1/country
Content-Type: application/json

{
  "country" : "German"
}

### Update address location
PATCH http://localhost:8080/user-management/users/1/address-management/addresses/1/location
Content-Type: application/json

{
  "location" : "Berlin"
}

### Update address zip code
PATCH http://localhost:8080/user-management/users/1/address-management/addresses/1/zip-code
Content-Type: application/json

{
  "zipCode" : "20-000"
}

### Update address street
PATCH http://localhost:8080/user-management/users/1/address-management/addresses/1/street
Content-Type: application/json

{
  "street" : "street"
}

### Delete address
DELETE http://localhost:8080/user-management/users/1/address-management/addresses/1