### Add product
POST http://localhost:8080/product-management/products
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTk4MTY0NzUwLCJpYXQiOjE1OTgwNzgzNTB9.9_npv0lZjcwau2q0TMxCG3sYvLNHKPbOyB9LEeV6iyM

{
  "name" : "Black Shorts",
  "prize" : "30.99"
}

### Update product
PUT http://localhost:8080/product-management/products/1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTk4MTY0NzUwLCJpYXQiOjE1OTgwNzgzNTB9.9_npv0lZjcwau2q0TMxCG3sYvLNHKPbOyB9LEeV6iyM

{
  "name" : "Red Shorts",
  "prize" : "20.00"
}

### Find product
GET http://localhost:8080/product-management/products/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTk4MTY0NzUwLCJpYXQiOjE1OTgwNzgzNTB9.9_npv0lZjcwau2q0TMxCG3sYvLNHKPbOyB9LEeV6iyM

### Find all products
GET http://localhost:8080/product-management/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTk4MTY0NzUwLCJpYXQiOjE1OTgwNzgzNTB9.9_npv0lZjcwau2q0TMxCG3sYvLNHKPbOyB9LEeV6iyM

### Delete product
DELETE http://localhost:8080/product-management/products/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZSIsImlzcyI6ImF1dGgwIiwiZXhwIjoxNTk4MTY0NzUwLCJpYXQiOjE1OTgwNzgzNTB9.9_npv0lZjcwau2q0TMxCG3sYvLNHKPbOyB9LEeV6iyM