### Realize transaction
POST http://localhost:8080/transaction-management/transactions
Content-Type: application/json

{
  "user" : {
    "id" : "1"
  },
  "product" : {
    "id" : "1"
  }
}